version: "3.9"
services:
  nombre1:
    build: .
    ports:
      - "3000:3000"
    links:
      -nombre2
  nombre2:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password